import os
import glob
import pandas as pd

# Path to the Parquet dataset directory generated by Spark
PARQUET_DIR = os.path.join("output", "health_advisories_parquet")

def analyze_parquet_outputs():
    """
    Reads streaming Parquet output files generated by Spark Structured Streaming
    and generates summary statistics for reports and verification.
    """
    print("=" * 70)
    print(" URBANPULSE PARQUET DATASET ANALYZER ")
    print("=" * 70)

    # 1. Check if directory exists
    if not os.path.exists(PARQUET_DIR):
        print(f"[ERROR] Directory '{PARQUET_DIR}' not found!")
        print("Please ensure your PySpark advisory job has run and generated output.")
        return

    try:
        # 2. Find all parquet files recursively inside the directory
        parquet_files = glob.glob(os.path.join(PARQUET_DIR, "**", "*.parquet"), recursive=True)
        
        # If no .parquet extension found, try finding part files directly
        if not parquet_files:
            parquet_files = [
                f for f in glob.glob(os.path.join(PARQUET_DIR, "**", "*"), recursive=True)
                if "part-" in os.path.basename(f) and not f.endswith(".crc")
            ]

        if not parquet_files:
            print("[WARN] No completed Parquet micro-batch files found yet.")
            print("Make sure your Spark job is actively running and generating health advisories!")
            return

        print(f"[INFO] Found {len(parquet_files)} data partition file(s). Loading...")

        # 3. Read found parquet files into Pandas
        df_list = [pd.read_parquet(f) for f in parquet_files]
        df = pd.concat(df_list, ignore_index=True)

        if df.empty:
            print("[WARN] Parquet files exist but contain 0 records.")
            return

        # 4. Overall Dataset Summary
        total_records = len(df)
        unique_zones = df['zone'].nunique() if 'zone' in df.columns else 0
        
        print(f"\n[INFO] Total Health Advisories Logged: {total_records}")
        print(f"[INFO] Unique Affected Zones Captured: {unique_zones}\n")

        # 5. Preview Top 5 Records
        print("--- Top 5 Recorded Health Advisories ---")
        preview_cols = [c for c in ['window_start', 'window_end', 'zone', 'zone_name', 'rolling_avg_aqi'] if c in df.columns]
        print(df[preview_cols].head(5).to_string(index=False))

        # 6. Zone-wise Advisory Summary Metrics
        if 'zone' in df.columns and 'rolling_avg_aqi' in df.columns:
            print("\n--- Zone-Level AQI Summary Breakdown ---")
            group_cols = [c for c in ['zone', 'zone_name'] if c in df.columns]
            zone_summary = df.groupby(group_cols).agg(
                total_advisories=('rolling_avg_aqi', 'count'),
                mean_aqi=('rolling_avg_aqi', 'mean'),
                max_aqi=('rolling_avg_aqi', 'max')
            ).reset_index()

            zone_summary['mean_aqi'] = zone_summary['mean_aqi'].round(2)
            print(zone_summary.to_string(index=False))

        print("\n" + "=" * 70)
        print("[SUCCESS] Parquet analysis complete!")
        print("=" * 70)

    except Exception as e:
        print(f"[ERROR] Failed to read Parquet dataset: {str(e)}")

if __name__ == "__main__":
    analyze_parquet_outputs()